### ISSUE TITLE
No recent update, still compatible ?

### ISSUE THREAD

**Issue by mohierf** [nicolargo/checkglances#7]
Is this plugin still compatible with Glances 2.5 version ?

Since there as been no recent update, what is the status of this plugin ? Known bugs ? Required improvements ?

**Comment by nicolargo** [comment]
Yes works like a charm with Glances 2.5.1 (last stable version):

Start Glances server on the server side:

    $ glances -s

Use Check Glances on the Nagios server:

[nicolargo:~/dev/checkglances] master 3 ± ./checkglances.py -H 127.0.0.1 -s cpu -v
Verbose mode ON
Check host: 127.0.0.1
Others args: {'statparam': '', 'stat': 'cpu', 'password': '', 'port': 61209}
{u'nice': 0.0, u'softirq': 0.0, u'iowait': 0.2, u'system': 0.7, u'idle': 92.9, u'user': 6.2, u'guest_nice': 0.0, u'irq': 0.0, u'total': 7.1, u'steal': 0.0, u'guest': 0.0}
Warning threshold: 70
Critical threshold: 90
CPU consumption: 7.10% | 'percent'=7.10;0;100;70;90 'nice'=0.00 'softirq'=0.00 'iowait'=0.20 'system'=0.70 'idle'=92.90 'user'=6.20 'guest_nice'=0.00 'irq'=0.00 'total'=7.10 'steal'=0.00 'guest'=0.00

[nicolargo:~/dev/checkglances] master ± ./checkglances.py -H 127.0.0.1 -s cpu
CPU consumption: 7.40% | 'percent'=7.40;0;100;70;90 'nice'=0.00 'softirq'=0.00 'iowait'=0.00 'system'=2.20 'idle'=92.60 'user'=5.20 'guest_nice'=0.00 'irq'=0.00 'total'=7.80 'steal'=0.00 'guest'=0.00

[nicolargo:~/dev/checkglances] master ± ./checkglances.py -H localhost -s load
LOAD last 5 minutes: 0.47 | 'cpucore'=4.00 'min1'=1.17 'min5'=0.47;4;20 'min15'=0.30
[nicolargo:~/dev/checkglances] master 127 ± ./checkglances.py -H localhost -s mem
MEM consumption: 49.90% | 'available'=4089827328.00 'used'=4068040704.00 'cached'=1353252864.00 'percent'=49.90 'free'=4089827328.00 'inactive'=1138622464.00 'active'=3688554496.00 'total'=8157868032.00 'buffers'=1671168.00

[nicolargo:~/dev/checkglances] master ± ./checkglances.py -H localhost -s swap
SWAP consumption: 2.60% | 'used'=430628864.00 'percent'=2.60 'free'=16346583040.00 'sout'=920666112.00 'total'=16777211904.00 'sin'=373301248.00

[nicolargo:~/dev/checkglances] master 3 ± ./checkglances.py -H localhost -s net -e enp0s25
Network rate: 14286 | 'tx'=11339 'cumulative_rx'=5809736891 'rx'=14286 'cumulative_cx'=6624980724 'time_since_update'=23.5283858776 'cx'=25625 'cumulative_tx'=815243833 'key'=interface_name 'interface_name'=enp0s25

[nicolargo:~/dev/checkglances] master ± ./checkglances.py -H localhost -s fs -e /
FS using space: 10% | 'mnt_point'=/ 'used'=10598752256 'percent'=10.1 'free'=94207647744 'device_name'=/dev/mapper/cl-root 'fs_type'=xfs 'key'=mnt_point 'size'=104806400000 'pctfree'=10.1%;70;90;0;100

**Comment by mohierf** [comment]
Thanks @nicolargo

I am testing it with a fresh Shinken installation and I think I will propose a PR ...
